### ISSUE TITLE
Feature Request: Start VM headless

### ISSUE THREAD

**Issue by hushnecampus** [eugene-rom/vbox-applet#2]
I have several VMs that I never want to see the console for, and I'd love an easy way to control when they're running and when they're suspended.  It'd be great if I could use the exention to switch them between running (headless) state and not-running (state saved) state.

**Comment by daalja** [comment]
Resolved starting headless in f1e09a7.

**Comment by eugene-rom** [comment]
Here is the fork with this feature - https://github.com/daalja/vbox-applet/tree/resolve-feat_req-headless
Personally I don't want add this functionality to my extensions.
