### ISSUE TITLE
Update to Gnome Shell 3.36

### ISSUE THREAD

**Issue by galen1423** [eugene-rom/vbox-applet#3]
Hi,

Thank you for this usefull extension. Can you consider to upgrade your code to Gnome Shell 3.36.

`Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?`

**Comment by galen1423** [comment]
Hi eugene,

I have tried your new code (v5 unreview) and it work as expected. We just have to wait for it to be validated...

**Comment by eugene-rom** [comment]
@galen1423, thank you for test.
